### PR TITLE
Code Box vs. CodeBox

### PR DESCRIPTION
**Pull request by badcat**
Change all instances of "Code Box" to "CodeBox" for consistency.
- Naming of product was inconsistent in code, docs etc.
- New Logo will use "CODEBOX" in all capital letters.

(Will change some icons next, but the videos, gifs etc should also change to keep the brand name consistent too)

### CODE REVIEW

**Comment by virejdasani** [comment]
@badcat, thanks a lot, these look awesome!

**Comment by virejdasani** [comment]
@badcat can I ask what software you used to create this logo and the animation?

**Comment by badcat** [comment]
@virejdasani Sure. The animation was done in Keyshape app. The original vector drawing was started in Affinity Designer.

**Comment by virejdasani** [comment]
@badcat Thanks a lot!

**Pull request merged**
